version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into docker
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - docker build -t ${tag}:latest .
      - docker tag $tag:latest $ecr:$tag
      - docker push $ecr
      - printf '[{"name":"container","imageUri":"%s"}]' ${ecr} > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
